application: certification-center
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.app

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /login
  script: login.app
  login: required

- url: /register
  script: register.app
  login: required

- url: /admin
  script: admin.app
  login: admin
  
- url: /publickey
  script: publickey.app

- url: /doverify
  script: doverify.app

- url: /*
  script: notfound.app

libraries:
- name: pycrypto
  version: "2.3"
