application: certification-center
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.app

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /login
  script: login.app

- url: /register
  script: register.app

- url: /*
  script: notfound.app
